### ISSUE TITLE
How can I set sudo password?

### ISSUE THREAD

**Issue by Esfahan** [volanja/ansible_spec#120]
I need to set sudo password with ansible_spec.
So, I tried following command.

```
$ ASK_SUDO_PASSWORD=1 bundle exec rake all
```

But the below error appeared.

```
Please set sudo password to Specinfra.configuration.sudo_password.
```

Therefore, I cheked spec/spec_helper.rb and I found below lines.

```rb
  if ENV['ASK_BECOME_PASSWORD']
    begin
      require 'highline/import'
    rescue LoadError
      fail "highline is not available. Try installing it."
    end
    set :become_password, ask("Enter become password: ") { |q| q.echo = false }
  else
    set :become_password, ENV['BECOME_PASSWORD']
  end
```

There are some differences from serverspec.
`set become_password` is defined instead of `set :sudo_password` in ansible_spec.

So, I fixed as follows by reference to serverspec.

```diff
-  if ENV['ASK_BECOME_PASSWORD']
+  if ENV['ASK_SUDO_PASSWORD']
    begin
      require 'highline/import'
    rescue LoadError
      fail "highline is not available. Try installing it."
    end
-    #set :become_password, ask("Enter become password: ") { |q| q.echo = false }
+    set :sudo_password, ask("Enter sudo password: ") { |q| q.echo = false }
  else
-    #set :become_password, ENV['BECOME_PASSWORD']
+    set :sudo_password, ENV['SUDO_PASSWORD']
  end
```

Now, I have been able to execute it with following command.

```
$ ASK_SUDO_PASSWORD=1 bundle exec rake all

or

$ export SUDO_PASSWORD=xxxx
$ bundle exec rake all
```

Why is the function implemented with different way from serverspec?
Which is the better way to set sudo password?

Best regards

**Comment by volanja** [comment]
Yes. ansible_spec is not support `ASK_SUDO_PASSWORD`.
Please use `BECOME_BECOME_PASSWORD`

Because Ansible use word that `become` instead of `sudo` after Ansible 1.9.

ref #111

**Comment by volanja** [comment]
I found [your post](https://qiita.com/Esfahan/items/06c9a18be5b3120f460b)
I think that this problem caused by mismatch between ansible_spec and serverspec.
Hmmm

**Comment by Esfahan** [comment]
@volanja 
I appreciate your cooperation. 
https://github.com/volanja/ansible_spec/pull/125
