### ISSUE TITLE
no implicit conversion of nil into Array Error when process get_parent

### ISSUE THREAD

**Issue by shogos3** [volanja/ansible_spec#126]
Example host inventory of ansible
```
[HOGE]
host1
 host2
host3	
	host4
host5	
```
host2 has a space before string like '[space]host2'.
host3 has a space after string like 'host3[space] '. 
host4 has a tab before string like '[tab]host4'.
host5 has a tab after string like 'host5[tab]'.

Ansible strips space/tab when loading hosts.

```
$ ansible-inventory -i hosts  --list
--- snip ---
    "HOGE": {
        "hosts": [
            "host1",
            "host2",
            "host3",
            "host4",
            "host5"
        ]
    },
```

But ansible_spec does not strip space/tabs.

```
"[HOGE]"
"host1"
" host2"
"host3 "
"\thost4"
"\thost5\t "
```
This causes "no implicit conversion of nil into Array" Error when process get_parent method.
Example host inventory of ansible:

```
[HOGE]
hoge1
hoge2
hoge3

[HOGEHOGE:children]
 HOGE
```

Exception:
```
no implicit conversion of nil into Array
```

It will be solved by following change, use "strip" insead of "chomp" in load_ansible.rb.

```
--- load_ansible.rb.old 2019-05-10 11:02:44.126640188 +0900
+++ load_ansible.rb     2019-05-10 11:03:11.118040115 +0900
@@ -26,7 +26,7 @@
     hosts = Hash.new
     hosts.default = Hash.new
     f.each_line{|line|
-      line = line.chomp
+      line = line.strip
       # skip
       next if line.start_with?('#') #comment
       next if line.empty? == true   #null
```

Thanks

**Comment by volanja** [comment]
Thank you for good  suggestion.
Cloud you create new pull request?
If unittest successful , I will merge it.

**Comment by volanja** [comment]
Thank you for your contribution!
