### ISSUE TITLE
Support hostlist expressions

### ISSUE THREAD

**Issue by udondan** [volanja/ansible_spec#13]
In Ansible you can define hosts as expressions.

`host-[1-3]` would expand into:
```
host-1
host-2
host-3
```

When reading the same inventory files this should be covered in `ansible_spec`.

I'm currently working with your great approach and just implemented this here. I released a gem which will make it easy for you to implement it in ansible_spec:

https://github.com/udondan/hostlist_expression-ruby
https://rubygems.org/gems/hostlist_expression

**Comment by volanja** [comment]
I Supported hostlist.
Thank you nice gems.

**Comment by volanja** [comment]
I released v0.1 that include hostlist expression.
