### ISSUE TITLE
Few clarifications on how to use this please

### ISSUE THREAD

**Issue by itsme-narahari** [volanja/ansible_spec#136]
Hello:
Sorry for my ignorance, so please bear with me.

Thank you in advance for your help.

Do I need to expect ruby on the target nodes ?

Do I need install spec_helper.rb  on the target nodes ?

or

this tool will parse thru my playbooks and roles and generate a diff set of test playbooks ?

Sorry for my ignorance but I am trying to get a handle on this.

-Narahari

**Comment by volanja** [comment]
+ Do I need to expect ruby on the target nodes ?
No, you don't need to install on the target nodes.
+ Do I need install spec_helper.rb on the target nodes ?
No, you don't need to install on the target nodes.
+ this tool will parse thru my playbooks and roles and generate a diff set of test playbooks ?
No, this tool is not generate test code.
