### ISSUE TITLE
Nested variables do not expand

### ISSUE THREAD

**Issue by alanraison** [volanja/ansible_spec#95]
If an Ansible variable is declared in terms of another variable; for example:

```
user: foo
base_folder: /home/{{user}}/bar
```

Then the property expansion of 'base_folder' (e.g. `file(property['base_folder'])`) only resolves one level, i.e. to `/home/{{user}}/bar` when ansible itself would resolve this to `/home/foo/bar`.

I am using ansible_spec 0.2.17

**Comment by RebelCodeBase** [comment]
This is the single biggest problem of this gem as it renders it useless for complex playbooks. (The other was ansible-vault support but I've created a [pull request](https://github.com/volanja/ansible_spec/pull/116) for this already).

**Comment by RebelCodeBase** [comment]
I've added this feature and opened a pull request: #117

**Comment by volanja** [comment]
I released v0.2.24 (merged #117)
